# Generated by Django 3.0.3 on 2020-02-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_birth', models.DateTimeField(verbose_name='birth date')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_autor_info', models.CharField(max_length=303)),
                ('book_name', models.CharField(max_length=1024)),
                ('book_genre', models.CharField(max_length=32)),
                ('_book_year', models.PositiveSmallIntegerField()),
                ('book_description', models.TextField()),
                ('book_autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapp.Autor')),
            ],
        ),
    ]
