# Generated by Django 3.0.3 on 2020-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='date_birth',
            field=models.DateField(verbose_name='birth date'),
        ),
    ]
