# Generated by Django 3.0.3 on 2020-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20200215_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='_book_year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
