# Generated by Django 3.0.3 on 2020-02-16 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20200216_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='_book_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2020, 'Год должен быть не больше чем тукущий')]),
        ),
    ]
