# Generated by Django 3.0.2 on 2020-02-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20200216_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='_book_year',
            new_name='book_year',
        ),
    ]
