# Generated by Django 3.0.3 on 2020-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20200218_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='autor',
            name='author_full_name',
            field=models.CharField(default=None, max_length=303),
            preserve_default=False,
        ),
    ]
