# Generated by Django 3.0.3 on 2020-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_auto_20200221_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='author_picture',
            field=models.ImageField(default=None, upload_to='C:/Users/Марина/Desktop/practice'),
            preserve_default=False,
        ),
    ]
