# Generated by Django 3.0.3 on 2020-02-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_autor_author_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='author_picture',
        ),
    ]
