# Generated by Django 3.0.3 on 2020-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_auto_20200223_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='birth_place',
            field=models.CharField(default=None, max_length=90),
        ),
        migrations.AddField(
            model_name='autor',
            name='death_date',
            field=models.DateField(default=None, verbose_name='death date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='author_full_name',
            field=models.CharField(default=None, max_length=303),
        ),
        migrations.AlterField(
            model_name='autor',
            name='author_picture',
            field=models.ImageField(default=None, upload_to='bookapp/static/bookapp/pictures'),
        ),
    ]
