# Generated by Django 3.0.3 on 2020-03-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_book_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='author_picture',
            field=models.ImageField(default='bookapp/static/bookapp/pictures/undefiend.png', upload_to='bookapp/static/bookapp/pictures'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_picture',
            field=models.ImageField(default='bookapp/static/bookapp/pictures/undefiend.png', upload_to='bookapp/static/bookapp/pictures'),
        ),
    ]
